import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import { Barlow } from 'next/font/google';

const barlow = Barlow({
  subsets: ['latin'],
  weight: ['100' , '200','300','400', '600', '700', '800', '900'],
  display: 'swap',
});

export const metadata = {
  title: "Shayan-Royal",
  description: "Generated by create next app",
};



export default async function RootLayout({ children }) {


  return (
    <html lang="en" >
      <body className={barlow.className}> 
        <Header />
        <main className="flex-grow">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
